// src/main/frontend_react/src/js/components/UserComponent.js
import React from 'react';

import {bindActionCreators} from 'redux'

import {connect} from 'react-redux'

import {isBlank, isInteger} from '../utils/CommonUtil'

import {Table, Form, Row, Col, Input, Button, message} from 'antd';

import {addUser, loadUsers} from '../actions/UserAction'
import {changeLocale} from '../actions/LocaleAction'

import {FormattedMessage, injectIntl} from 'react-intl'

const columns = [{
    title: <FormattedMessage id="label.name"/>,
    dataIndex: 'name',
}, {
    title: <FormattedMessage id="label.age"/>,
    dataIndex: 'age',
}, {
    title: <FormattedMessage id="label.address"/>,
    dataIndex: 'address',
}];

const INIT_PAGE_SIZE = 5;

class UserComponent extends React.Component {

    constructor(props){
        super(props);
        this.state = {
            name: '',
            age: '',
            address: '',
            page: 1,
            pageSize : INIT_PAGE_SIZE
        };
    }

    componentDidMount() {
        this.loadUsers();
    }

    addUser() {
        if (isBlank(this.state.name)) {
            message.error(this.props.intl.formatMessage({id: 'validate.nameIsEmpty'}));
            return;
        }

        if (isBlank(this.state.age)) {
            message.error(this.props.intl.formatMessage({id: 'validate.ageIsEmpty'}));
            return;
        }

        if (!isInteger(this.state.age)) {
            message.error(this.props.intl.formatMessage({id: 'validate.ageIsInvalid'}));
            return;
        }

        if (isBlank(this.state.address)) {
            message.error(this.props.intl.formatMessage({id: 'validate.addressIsEmpty'}));
            return;
        }

        this.props.addUser(this.state.name, parseInt(this.state.age || 0, 10), this.state.address).then(() => {
            this.setState({
                name: '',
                age: '',
                address: '',
                page: 1
            }, () => {
                this.loadUsers();
            });
        });
    }

    loadUsers() {

        let filters = {};

        if (!isBlank(this.state.name)) {
            filters.name = this.state.name;
        }

        if (!isBlank(this.state.age) && isInteger(this.state.age)) {
            filters.age = parseInt(this.state.age || 0, 10);
        }

        if (!isBlank(this.state.address)) {
            filters.address = this.state.address;
        }

        this.props.loadUsers(this.state.page, this.state.pageSize, filters);
    }

    changeLocale() {
        this.props.changeLocale();
    }

    render() {
        if (!isBlank(this.props.errMsg)) {
            message.error(this.props.errMsg);
        }
        let pagination = {
            onChange: (page) => this.setState({
                page: page
            }, () => this.loadUsers()),
            current: this.state.page,
            pageSize: this.state.pageSize,
            total: this.props.total,
            showSizeChanger: true,
            pageSizeOptions: ['5', '10', '20', '40'],
            onShowSizeChange: (page, pageSize) => this.setState({
                page: 1,
                pageSize: pageSize
            }, ()=> this.loadUsers())
        };
        let formItemLayout = {
            labelCol: {span: 8},
            wrapperCol: {span: 16},
        };
        return (
            <div className="panel panel-primary" style={{maxWidth: 800, margin: '10px auto 10px'}}>
                <div className="panel-heading">
                    Demo <Button onClick={() => this.changeLocale()}>{<FormattedMessage id="label.changeLocale"/>}</Button>
                </div>
                <div className="panel-body">
                    <Form
                        horizontal
                        style={{marginBottom: 15}}
                    >
                        <Row>
                            <Col span={8}>
                                <Form.Item {...formItemLayout} label={<FormattedMessage id="label.name"/>}>
                                    <Input type="text" value={this.state.name || ''}
                                           onChange={(e) => this.setState({name : e.target.value.trim()})}/>
                                </Form.Item>
                            </Col>
                            <Col span={8}>
                                <Form.Item {...formItemLayout} label={<FormattedMessage id="label.age"/>}>
                                    <Input type="text" value={this.state.age || ''}
                                           onChange={(e) => this.setState({age : e.target.value.trim()})}/>
                                </Form.Item>
                            </Col>
                            <Col span={8}>
                                <Form.Item {...formItemLayout} label={<FormattedMessage id="label.address"/>}>
                                    <Input type="text" value={this.state.address || ''}
                                           onChange={(e) => this.setState({address : e.target.value.trim()})}/>
                                </Form.Item>
                            </Col>
                        </Row>
                        <Row>
                            <Col span={18}/>
                            <Col span={6}>
                                <Button type="primary" onClick={() => this.addUser()}
                                        style={{marginLeft: 10, marginRight: 10}}>{<FormattedMessage id="label.add"/>}</Button>
                                <Button type="primary" onClick={() => this.setState({page: 1}, () => this.loadUsers())}
                                        style={{marginLeft: 10, marginRight: 10}}>{<FormattedMessage id="label.search"/>}</Button>
                            </Col>
                        </Row>
                    </Form>
                    <Table dataSource={this.props.users} rowKey="id" columns={columns} pagination={pagination}
                           loading={this.props.loading}/>

                </div>
            </div>
        );
    }
}

//如果组件需要读取store里的状态或需要触发action，则需要用decorator方式注入必要的属性
export default connect(
    state => ({
        total: state.userState.total,
        users: state.userState.users,
        errMsg: state.userState.errMsg,
        loading: state.userState.loading
    }),
    dispatch => ({
        ...bindActionCreators({
            addUser,
            loadUsers,
            changeLocale
        }, dispatch)
    })
)(injectIntl(UserComponent));

// src/main/frontend_vue/src/js/components/UserComponent.vue
<template>
  <div class="panel panel-primary" style="maxWidth: 800px; margin: 10px auto 10px;">
    <div class="panel-heading">
        Demo <el-button @click="changeLocale">{{$t('label.changeLocale')}}</el-button>
    </div>
    <div class="panel-body">
        <el-form :inline="true" class="demo-form-inline">
            <el-row>
                <el-col :span="8">
                    <el-form-item :label="$t('label.name')">
                        <el-input v-model="name"></el-input>
                    </el-form-item>
                </el-col>
                <el-col :span="8">
                    <el-form-item :label="$t('label.age')">
                        <el-input v-model="age"></el-input>
                    </el-form-item>
                </el-col>
                <el-col :span="8">
                    <el-form-item :label="$t('label.address')">
                        <el-input v-model="address"></el-input>
                    </el-form-item>
                </el-col>
            </el-row>
            <el-row>
                <el-col :offset="16" :span="8">
                    <el-button @click="addUser">{{$t('label.add')}}</el-button>
                    <el-button @click="loadUsers">{{$t('label.search')}}</el-button>
                </el-col>
            </el-row>
        </el-form>
        <el-table v-loading="loading"
                :data="users"
                style="width: 100%; margin: 10px 0px;">
            <el-table-column
                    prop="name"
                    :label="$t('label.name')">
            </el-table-column>
            <el-table-column
                    prop="age"
                    :label="$t('label.age')">
            </el-table-column>
            <el-table-column
                    prop="address"
                    :label="$t('label.address')">
            </el-table-column>
        </el-table>
        <el-pagination align="right"
                layout="prev, pager, next, total, sizes"
                :total="total" :page-sizes="[5, 10, 20, 40]"  :current-page="page" @current-change="pageChanged"  :page-size="pageSize" @size-change="pageSizeChanged">
        </el-pagination>
    </div>
  </div>
</template>

<script>
  import Vue from 'vue'
  import { mapState } from 'vuex'
  import {isBlank, isInteger} from '../utils/CommonUtil'
  import {ACTION_LOAD_USERS, ACTION_ADD_USER} from '../constants/UserConstant'
  import {ACTION_CHANGE_LOCALE} from '../constants/LocaleConstant'

  const INIT_PAGE_SIZE = 5;

  export default {
      name : 'UserComponent',

      data : function(){
          return {
              name: '',
              age: '',
              address: '',
              page: 1,
              pageSize: INIT_PAGE_SIZE,
              loading: false
          };
      },

      computed : {
        ...mapState({
            users : state => state.userStore.users,
            total: state => state.userStore.total,
            errMsg: state => state.userStore.errMsg
        })
      },

      mounted(){
          this.loadUsers();
      },

      beforeUpdate(){
        if(!isBlank(this.errMsg)){
          this.$message.error(this.errMsg);
        }
      },

      methods : {
          changeLocale : function(){
              this.$store.dispatch(ACTION_CHANGE_LOCALE);
          },
          addUser : function(){
              if (isBlank(this.name)) {
                  this.$message.error(this.$t('validate.nameIsEmpty'));
                  return;
              }

              if (isBlank(this.age)) {
                  this.$message.error(this.$t('validate.ageIsEmpty'));
                  return;
              }

              if (!isInteger(this.age)) {
                  this.$message.error(this.$t('validate.ageIsInvalid'));
                  return;
              }

              if (isBlank(this.address)) {
                  this.$message.error(this.$t('validate.addressIsEmpty'));
                  return;
              }

              this.$store.dispatch(ACTION_ADD_USER, {name: this.name, age: parseInt(this.age || 0, 10), address: this.address}).then(() => {
                  this.name = '';
                  this.age = '';
                  this.address = '';
                  this.page = 1;
                  this.loadUsers();
              });
          },
          loadUsers : function(){
              this.loading = true;
              let filters = {};
              if (!isBlank(this.name)) {
                  filters.name = this.name;
              }

              if (!isBlank(this.age) && isInteger(this.age)) {
                  filters.age = parseInt(this.age || 0, 10);
              }

              if (!isBlank(this.address)) {
                  filters.address = this.address;
              }
              this.$store.dispatch(ACTION_LOAD_USERS, {page: this.page, pageSize: this.pageSize, filters: filters}).then(() => {
                this.loading = false;
              });
          },
          pageChanged: function(page){
              this.page = page;
              this.loadUsers();
          },
          pageSizeChanged: function(pageSize){
              this.page = 1;
              this.pageSize = pageSize;
              this.loadUsers();
          }
      }
  }

</script>
